# https://taskfile.dev

version: "3"

vars:
  WORK_DIR: zig-out/bin/

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list-all
    silent: true
  build:
    desc: Builds the wasm module
    cmds:
      - zig build bouncing_lines
    silent: true
  run:
    desc: Starts the application server
    cmds:
      - http-server {{.WORK_DIR}} -o -p 9000 -c-1
